# Generated by Django 2.1.5 on 2021-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='1', upload_to='products'),
            preserve_default=False,
        ),
    ]
